version: "3.8"

networks:
  test:
services: 
  elasticsearch:
    # image: 'nginx:stable-alpine'
    image: elasticsearch:8.3.2
    ports: 
      - '9200:9200'    
    expose:
      - 9200
    networks:
      - test
  kibana:
    image: kibana:8.3.2
    ports:
      - '5601:5601'
    networks:
      - test
  apitesting:
    build:
      context: ./
      dockerfile: Dockerfile
    # logging:
    #   driver: "fluentd"
    #   options:
    #     fluentd-address: localhost:24224
    #     tag: api.testing
    ports:
      - '9876:9876'
    networks:
      - test
    links:
      - fluentd
    depends_on: 
      - kibana
      - elasticsearch
      - fluentd
  fluentd:
    build:
      context: ./
      dockerfile: fluentd.dockerfile
    ports:
      - '24224:24224'
      - '24224:24224/udp'
    volumes:
      - ./fluentd/conf:/fluentd/etc
    networks:
      - test
  # mysql:
  #   image: mysql:5.7
  #   environment:
  #     - MYSQL_DATABASE=homestead
  #     - MYSQL_USER=homestead
  #     - MYSQL_PASSWORD=secret
  #     - MYSQL_ROOT_PASSWORD=secret
  #   # env_file: 
  #   #   - ./env/mysql.env
