{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    {{- include "common.labels" . | nindent 4 }}
  name: {{ include "common.fullname" . }}
spec:
  host: "{{ .Values.name }}.{{ .Values.host }}"
  path:
  port:
    targetPort: "{{ .Values.service.port }}-{{ .Values.service.protocol | lower }}"
  to:
    kind: Service
    name: {{ include "common.fullname" . }}
    weight: {{ .Values.service.weight }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None
status:
  ingress:
    - conditions:
      host: "{{ .Values.name }}-{{ .Values.host }}"
      routerName: router
      wildcardPolicy: None
      routerCanonicalHostname: {{ .Values.host }}
{{- end }}
